#' time match logger data
#'
#' @description timematch of simoultaneously received signals by stations 
#'
#'
#' @author Jannis Gottwald
#'
#'
#' 
#' @param animal list, list generated by initAnimal functiom
#' @param method string, which bearing calculation method ("linear", "acos", "ML")
#' @param collision logical, if collision corrected data is used a suffix is added to resulting file name
#' 
#'
#' @export
#'
#'


time_match_station<-function(data, method, tmstmp){
#get timenatches-
  

data$timestamp<-as.character(tmstmp)
grid<-expand.grid(unique(data$station),unique(data$station))
grid<-grid[grid$Var1!=grid$Var2,]
indx <- !duplicated(t(apply(grid, 1, sort))) # finds non - duplicates in sorted rows
grid<-grid[indx, ] # selects only the non - duplicates according to that index

df<-data.frame()
for(i in 1:nrow(grid)){
  
tmp<-data[data$station==grid$Var1[i] | data$station==grid$Var2[i],]
dcst<-data.table::dcast(tmp, timestamp~station, value.var =method , mean)
dcst$name_s1<-names(dcst)[2]
dcst$name_s2<-names(dcst)[3]
colnames(dcst)<-c("timestamp", "s1", "s2", "name_s1", "name_s2")


df<-rbind(df, dcst)
}



return(df)

}




