#' adds meta data 
#'
#' @description adds meta data from idFile.rds to data
#'
#'
#' @author Jannis Gottwald
#'
#' @param animal list, generated by initAnimal function
#' @param projList list, generatet by initProject function
#' @param data data.frame, data frame data.table
#'
#' @export
#'
#'



add.ID.Info<-function( animal, data){
  
 
  
  data$ID<-animal$meta$animalID
  
  data$species<-animal$meta$species
  
  data$sex<-animal$meta$sex

  data$age<-animal$meta$age
  
  data$weight<-animal$meta$weight
  
  data$rep.state<-animal$meta$rep.state
  
  return(data)
  
}